[project]
name = "central"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "githubkit>=0.15.5",
    "httpx>=0.28.1",
    "pydantic>=2.13.4",
    "python-debian>=1.1.0",
]

[project.scripts]
fork = "altvault.fork:main"
generate = "altvault.generate:main"
outdated = "altvault.outdated:main"
tweak = "altvault.tweak:main"
upload = "altvault.upload:main"

[tool.uv]
exclude-newer = "24 hours"
package = true
