from altvault.helpers.models import (
    App,
    CydiaRepoDebFile,
    GitHubReleasesDebFile,
    Recipes,
    Tweak,
)
from altvault.helpers.config import config


_recipes = [
    App(
        name="Apollo",
        bundle_identifier="com.christianselig.Apollo",
        tweaks=[
            Tweak(
                name="ApolloReborn",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="Apollo-Reborn",
                        repo="Apollo-Reborn",
                        endswith="rootless.deb",
                        use_version=True,
                    )
                ],
            )
        ],
    ),
    App(
        name="Facebook",
        bundle_identifier="com.facebook.Facebook",
        tweaks=[
            Tweak(
                name="FacebookGlow",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="dayanch96",
                        repo="Glow",
                        endswith="arm64.deb",
                        use_version=True,
                    )
                ],
            )
        ],
    ),
    App(
        name="Infuse",
        bundle_identifier="com.firecore.infuse",
        tweaks=[
            Tweak(
                name="InfusePlus",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="dayanch96",
                        repo="InfusePlus",
                        endswith="arm64.deb",
                        use_version=True,
                    )
                ],
            )
        ],
    ),
    App(
        name="Instagram",
        bundle_identifier="com.burbn.instagram",
        tweaks=[
            Tweak(
                name="RyukGram",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="faroukbmiled",
                        repo="RyukGram",
                        endswith="rootless.deb",
                        use_version=True,
                    )
                ],
            ),
            Tweak(
                name="SCInsta",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="SoCuul",
                        repo="SCInsta",
                        endswith="rootless.deb",
                        use_version=True,
                    )
                ],
            ),
        ],
    ),
    App(name="TikTok", bundle_identifier="com.zhiliaoapp.musically"),
    # App(name="TikTokGlobal", bundle_identifier="com.ss.iphone.ugc.Ame"),
    App(
        name="X",
        bundle_identifier="com.atebits.Tweetie2",
        tweaks=[
            Tweak(
                name="BHTwitter",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="BandarHL",
                        repo="BHTwitter",
                        endswith="arm64.deb",
                        use_version=True,
                    )
                ],
            )
        ],
    ),
    App(
        name="YouTube",
        bundle_identifier="com.google.ios.youtube",
        tweaks=[
            Tweak(
                name="MyYouTube",
                deb_files=[
                    CydiaRepoDebFile(
                        repo="https://poomsmart.github.io/repo",
                        package="com.ps.ytabgoodies",
                        architecture="iphoneos-arm64",
                    ),
                    CydiaRepoDebFile(
                        repo="https://poomsmart.github.io/repo",
                        package="com.ps.ytx",
                        architecture="iphoneos-arm64",
                    ),
                    CydiaRepoDebFile(
                        repo="https://poomsmart.github.io/repo",
                        package="com.ps.ytvideooverlay",
                        architecture="iphoneos-arm64",
                    ),
                    CydiaRepoDebFile(
                        repo="https://poomsmart.github.io/repo",
                        package="com.ps.youpip",
                        architecture="iphoneos-arm64",
                    ),
                    GitHubReleasesDebFile(
                        owner="hbang",
                        repo="Alderis",
                        tag="1.2.3",
                        endswith="arm64.deb",
                    ),
                    CydiaRepoDebFile(
                        repo="https://repo.icrazeios.com",
                        package="com.galacticdev.isponsorblock",
                        architecture="iphoneos-arm64",
                    ),
                    GitHubReleasesDebFile(
                        owner=config.owner,
                        repo="YTStartupTab",
                        endswith="arm64.deb",
                    ),
                ],
            ),
            Tweak(
                name="YouMod",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="Tonwalter888",
                        repo="YouMod",
                        endswith="arm64.deb",
                        use_version=True,
                    ),
                    CydiaRepoDebFile(
                        repo="https://poomsmart.github.io/repo",
                        package="com.ps.ytvideooverlay",
                        architecture="iphoneos-arm64",
                    ),
                    CydiaRepoDebFile(
                        repo="https://poomsmart.github.io/repo",
                        package="com.ps.youpip",
                        architecture="iphoneos-arm64",
                    ),
                ],
            ),
        ],
    ),
    App(
        name="YouTubeMusic",
        bundle_identifier="com.google.ios.youtubemusic",
        tweaks=[
            Tweak(
                name="YTMusicUltimate",
                deb_files=[
                    GitHubReleasesDebFile(
                        owner="dayanch96",
                        repo="YTMusicUltimate",
                        endswith="arm64.deb",
                        use_version=True,
                    )
                ],
            )
        ],
    ),
]

recipes = Recipes(_recipes)
